### ISSUE TITLE
Stats not adjusted for timezone

### ISSUE THREAD

**Issue by Squashbucklr** [andersonkrs/malheatmap#294]
For a user in a time zone other than that of the server, the information on the graph is not the same as the information on the history page.

Example for GMT-4:
My history page says 6 episodes of SSSS.Dynazenon completed on 6/15 and 5 episodes completed on 6/14
malheatmap shows 4 episodes of SSSS.Dynazenon completed on 6/15 and 7 episodes completed on 6/14

With the times I completed episodes, it seems that all of the data on malheatmap is in GMT-6.

Expected behavior:
Either match the time zone of the user's profile, or adapt based on the time zone of the viewer.

**Comment by andersonkrs** [comment]
Hey @Squashbucklr

Good catch, thank you for reporting it, it should be fixed now.
If you look into your activities on MAL Heatmap you'll see now they are matching :)

![image](https://user-images.githubusercontent.com/3708060/122650643-87040d80-d10a-11eb-9d6d-fa076c34db2e.png)
![image](https://user-images.githubusercontent.com/3708060/122650617-5c19b980-d10a-11eb-833f-721720d6658d.png)

**Comment by andersonkrs** [comment]
Fixed with https://github.com/andersonkrs/malheatmap/commit/32af34a9dd1ed50d8cbb81ecadf85a8daef4eaca

**Comment by Squashbucklr** [comment]
Thanks so much for taking the time to look at this! I don't think it's been completely fixed, though. Here's what the same set of entries listed in your screenshots looks like from my side:
![Screenshot 2021-06-28 005444](https://user-images.githubusercontent.com/69176059/123582218-74917000-d7ab-11eb-8e8d-fe683d072a47.png)
As you can see, the dates that appear on my end do not match those on your end, however viewing malheatmap brings the same results as when you view it.

Here's another example of inconsistencies from my end:
![Screenshot 2021-06-28 005530](https://user-images.githubusercontent.com/69176059/123582288-8f63e480-d7ab-11eb-8da5-111c27b55bb2.png)
![Screenshot 2021-06-28 005548](https://user-images.githubusercontent.com/69176059/123582329-9a1e7980-d7ab-11eb-9949-b2d7bdcae57f.png)

The MAL history section is based on the **viewer**'s timezone in MAL's settings, which is only accessible to that user or an application with an API token for that user. Therefore I'm not sure it would be possible to generate a chart with dates specific to a viewer.

The best solution in my mind is to have the chart reflect the timezone of the profile rather than the viewer. For that you would have to store the profile's timezone in the DB and adjust from UTC.

The timezone could either be collected manually upon registration or by replacing registration by username or profile url with OAuth in order to make an API request to get the timezone. This would allow changing the timezone after registration (if a user moves).

**Comment by andersonkrs** [comment]
Ow I totally see,

Since MAL has this open beta API, it would be great to link your account on MAL with MAL Heatmap instead of just "subscribing."

Now we already store the timestamps as UTC and convert them to the user's location timezone. The real issue is that MAL Heatmap collects data as WebCrawler, so the returned HTML from where we extract the information is the same as an unlogged user on MAL viewing your profile. That's why such a difference.

I'm really excited about the API. It would be a great improvement to MAL Heatmap to rely on the public API data instead of manually crawling the website and extracting the data. I'm starting to study the API docs and see if we can do this big shift. That will be a long project, so it may take a while to get done.

The only thing that prevented me from using the API is that they do not have an endpoint to get the user history yet :cry: We would still need to do the crawling manually, but I'm not entirely sure how the API is working now, neither if it would be possible to use the OAuth to fetch the user data regularly. 

I appreciated your time putting all this info together for me, and I'll let you know as I progress on this.
Thank you!

**Comment by Squashbucklr** [comment]
Might want to re-open this issue btw.

> The real issue is that MAL Heatmap collects data as WebCrawler, so the returned HTML from where we extract the information is the same as an unlogged user on MAL viewing your profile. That's why such a difference.

If you know the time zone of the VPS that you run this project on, converting to UTC should be trivial.

> The only thing that prevented me from using the API is that they do not have an endpoint to get the user history yet.

Yeah, the API is lacking in features right now unfortunately. I've been waiting for them to add profile management (About Me, Character Favorites, etc...) so I can make some programs of my own that don't rely on images.

> neither if it would be possible to use the OAuth to fetch the user data regularly

In order to get the time zone of a user with the API, you need them to authorize the application since the time zone isn't publicly viewable information for security reasons. While it does take a while, the tokens do expire. However, if the user updates their time zone for some reason, then they could re-authorize the application so that their time zone could be reloaded.
Since history is publicly viewable, when the API ~~eventually~~ hopefully adds support, you probably won't need authorization to view it as long as their list is public.

> I appreciated your time putting all this info together for me, and I'll let you know as I progress on this.

No problem! I love these sorts of projects and should probably get around to making some of my own. I would totally help out on the code for this but I don't know any ruby. Though I can probably help with the API if needed.

**Comment by andersonkrs** [comment]
> Might want to re-open this issue btw.
>

Good call, done!

> If you know the time zone of the VPS that you run this project on, converting to UTC should be trivial.
> 

Well... that is not the case, the VPS is already running on UTC and the Rails app is also set up to use UTC for every date stored in the DB.

I think I finally figured it out, when a user is not logged in, like the crawler requests, the MAL's servers use the Pacific Time as a time zone in order to show the timestamps on the history page :neutral_face: So their app totally ignores the client's time zone (in my case the VPS server running on UTC). If a user is logged in it will use the time zone set on the user's MAL settings.

Therefore I had to change the code to parse the dates as they are in Pacific Time and then save them as UTC in the DB. So now if you look at your profile the dates will match because they are stored in UTC but converted to your time zone as they are shown on the UI.

![image](https://user-images.githubusercontent.com/3708060/123896945-eb0fa880-d938-11eb-9ad3-8fe49282205d.png)
![image](https://user-images.githubusercontent.com/3708060/123897019-1b574700-d939-11eb-89ac-d632e08dc971.png)

So I think it fixes the main issue. Always parse as Pacific -> Convert timestamps to the user's time zone based on the location.

> In order to get the time zone of a user with the API, you need them to authorize the application since the time zone isn't publicly viewable information for security reasons. While it does take a while, the tokens do expire. However, if the user updates their time zone for some reason, then they could re-authorize the application so that their time zone could be reloaded.
> Since history is publicly viewable, when the API ~eventually~ hopefully adds support, you probably won't need authorization to view it as long as their list is public.

Yeah, I see, about the token it's possible to store it on the DB and keep refreshing it to fetch updated data. 
In general, using OAuth would be way better and I would not need to handle a series of things anymore like if the user changes its username it would just work out of the box, nowadays it is not supported by MAL Heatmap. 

Also being able to get the user's time zone without relying on the user's location would be another good thing. Unfortunately, the MAL's API Policy does not explicitly allow an App to use web-crawling while using the API to fetch data, so I'll need some time to find that out. https://myanimelist.net/static/apiagreement.html

I think we can close this issue now right? I'll create another one as a TODO issue to implement OAuth, but that is going to take some time and also I'll need to create a way for existing users to link their accounts without losing their current data.

**Comment by Squashbucklr** [comment]
> when a user is not logged in, like the crawler requests, the MAL's servers use the Pacific Time as
the time zone in order to show the timestamps on the history page

Weird, I guess I should have checked that instead of using another account

> Unfortunately, the MAL's API Policy does not explicitly allow an App to use web-crawling while using the API to fetch data

Ah, didn't know about that. Certainly complicates some things. But yeah I think this is in as good of a state as it can possibly be until MAL allows the retrieval of the history page through the API. Thanks for the hard work looking over this!

**Comment by andersonkrs** [comment]
Fixed with https://github.com/andersonkrs/malheatmap/commit/1daa30191988b3c4a4b19dd3090faa27059c99a3
