### ISSUE TITLE
Mangas are being tracked incorrectly

### ISSUE THREAD

**Issue by Galtvam** [andersonkrs/malheatmap#299]
The first entry of a manga adds all the chapters from 1 to the read as entries.

For example, May 31, 2021:
* Kanojo, Okarishimasu **190 chapters**

And on Jun 10, 2021:
* Kanojo, Okarishimasu **1 chapter**

What happened was that the first entry, the read of chapter 190, added 190 entries, and on Jun 10th added 1 entry (chapter 191).

<hr>

The expected result would be: 

May 31, 2021:
* Kanojo, Okarishimasu **1 chapter**

And on Jun 10, 2021:
* Kanojo, Okarishimasu **1 chapter**

**Comment by andersonkrs** [comment]
@Galtvam Thanks for submitting the issue.

It is actually by design, not a bug. :slightly_smiling_face: 

The issue with MAL is that we cannot know exactly when you started to watch/read a show if MAL Heatmap can only see the last 21 days of your history. So for example, in the day 22 that is not showing anymore on your MAL profile, you could be at the chapter 100 for example, and let's say that you've read 3 new chapters in the following day, there's no way to know that you read 3 chapters as your first entry.

MAL Heatmap will just see that you started at the position 103 of that manga, since there is no position recorded before that day, your progressed 103 chapters. I know that is not the perfect world but it is just for the first activity for the given show, after the first one we will compute the difference as long as you add more entries to your MAL history.

Does that clarifies a little bit for you? There is also a section on the FAQ page highlight that behavior you'd like to check it out :smile: 
> Be aware that we compute the first entry of the show as current position. This means, for example, if you subscribe when you are in episode 63 of a show, the number of activities on that day will be 63. After that, we'll compute the difference from the last position, and so, new episodes will be registered in parallel to your MAL activity.
