### ISSUE TITLE
wrong time zone

### ISSUE THREAD

**Issue by DanielM51** [andersonkrs/malheatmap#417]
Even though I changed the time zone to my region (America/Sao_Paulo), it still shows the data wrong. 
Basically the site is registering some activities from yesterday as being today. How to fix?

**Comment by andersonkrs** [comment]
Hey Daniel! What is your MAL username?

**Comment by DanielM51** [comment]
DNovais

**Comment by andersonkrs** [comment]
Hey @DanielM51 can you try changing your location on MAL to `São Paulo, Brazil`
![image](https://user-images.githubusercontent.com/3708060/150900387-55ca574e-acde-445a-9ff6-3664b3a658d0.png)

We use this field to calculate the timezone, your timezone internally now is pointing to America/Cuiaba because your location is just "Brasil"

**Comment by DanielM51** [comment]
OK, thanks for the help.

**Comment by andersonkrs** [comment]
Did that work for you? Can we close this issue?

**Comment by DanielM51** [comment]
Yes

**Comment by andersonkrs** [comment]
Thanks!
