### ISSUE TITLE
Request for Darkmode / Transparent images for MAL BBCode

### ISSUE THREAD

**Issue by ekrekeler** [andersonkrs/malheatmap#760]
This is probably more of a request for niche users of global darkmode setting in browsers, but I would like to have the option for a transparent background or otherwise "dark" image for BBCode in MAL.

As an example, this renders fine on the main site when it is generated in HTML:
<img width="655" alt="malheatmap" src="https://github.com/andersonkrs/malheatmap/assets/10748166/14cbe231-53d1-4e33-8a0f-b4d504137000">

However the only image available for use in BBCode still has a white background, appearing a bit odd on a dark background in MAL profile:
<img width="795" alt="myanimelist" src="https://github.com/andersonkrs/malheatmap/assets/10748166/93cf3d6c-6017-4b30-9bb6-15d04fe0d451">

For those curious, the "darkmode" setting is available in chromium-based browsers and can be found at [chrome://flags/#enable-force-dark](chrome://flags/#enable-force-dark) . I have mine set to "Enabled with selective inversion of non-image elements".

**Comment by andersonkrs** [comment]
Nice suggestion, let me see what I can do

**Comment by andersonkrs** [comment]
@ekrekeler sorry for taking this long, but now all images are generated with a transparent background.

In addition to that, now there is a larger image variant, which ss better to use on your MAL profile page since it has a larger resolution.

<img width="1038" alt="image" src="https://github.com/user-attachments/assets/e3cd9062-1ff7-4c86-8588-567f5cdcfb00">

**Comment by ekrekeler** [comment]
Awesome!
I forgot about this as well, thanks for fixing this. I just checked with the "Large BB Code" on my profile and looks just like above.
