### ISSUE TITLE
incorrect heatmap with the recent update

### ISSUE THREAD

**Issue by GDjkhp** [andersonkrs/malheatmap#853]
![Screenshot_20240103-134548](https://github.com/andersonkrs/malheatmap/assets/51813377/9eae0613-aa9e-4ba5-b370-3319d4b7d0c1)
### 
that was heckin weird. nice to see this getting updated tho. happy new year btw.

**Comment by andersonkrs** [comment]
Happy new year!!

Could you elaborate a little more?

<img width="1148" alt="image" src="https://github.com/andersonkrs/malheatmap/assets/3708060/2959e38c-f759-4714-9ef3-a533d2b1447c">

From your history, before Jan, your last entry was on Dec 14. Therefore the gap there 🤔 

Just for clarification, the last year of the heatmap (2024) in this case, will show the current day as the end of the calendar and the past 365 days.

Instead of showing an empty 2024 calendar, we prefer to show as default your past year, to have a better sense at first glance without having to go back to the last year 2023 to see your activities.

I hope that's helpful, and stay tuned, I'll try to update this project more in 2024

**Comment by GDjkhp** [comment]
what i mean is, i've watched 12 episodes but it shows only 1

![image](https://github.com/andersonkrs/malheatmap/assets/51813377/7052a269-7453-4454-9f9c-5b56d830c471)
![image](https://github.com/andersonkrs/malheatmap/assets/51813377/16f568d5-d19a-47a0-a08a-1af75a94413f)

**Comment by andersonkrs** [comment]
My apologies, that was an issue indeed, I migrated the database to a new adapter and didn't see a setting was imported incorrectly.

It should be fixed now. Thank you for the report.

**Comment by GDjkhp** [comment]
oh also i forgot: example.com
![image](https://github.com/andersonkrs/malheatmap/assets/51813377/0362ebaf-cff3-4e3a-8047-9a0d802b9283)

**Comment by andersonkrs** [comment]
> oh also i forgot: example.com ![image](https://private-user-images.githubusercontent.com/51813377/298912041-0362ebaf-cff3-4e3a-8047-9a0d802b9283.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MzYwODUsIm5iZiI6MTcwNjQzNTc4NSwicGF0aCI6Ii81MTgxMzM3Ny8yOTg5MTIwNDEtMDM2MmViYWYtY2ZmMy00ZTNhLTgwNDctOWEwZDgwMmI5MjgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDA5NTYyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzZmFlMGMxZmE0MTg0OTg2MWM4MWNmNDQ4ZThlOTNmYmMwMGJkZjBkYzExNjAyM2U2ZWU1OTNiMjdjNzdhZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.k_fDkieM9q5BSbNGtuykxlh7L2bltc53E0AuQWFZf4Q)

Just pushed a fix, ty!
