### ISSUE TITLE
How does it work? just shows "Content missing"

### ISSUE THREAD

**Issue by cyber-sec0** [andersonkrs/malheatmap#922]
How does it work? just shows "Content missing"

**Comment by andersonkrs** [comment]
Please send me your username, I'll perform some checks here!

**Comment by Shark-93** [comment]
The title should've been, does it still work? 😀 Hello @andersonkrs I've signed myself up a couple of days ago but the page never advances past the _fetching your data from MyAnimeList and preparing it for you_ initial setup (user: [S_h_a_r_k_93](https://malheatmap.com/users/S_h_a_r_k_93)).

I saw the heatmap from iHateAnimeBro's (awesome) profile and if you check his [last anime updates](https://myanimelist.net/profile/iHateAnimeBro#statistics) you'll see after December 2023 he made one update, right? But [his heatmap](https://malheatmap.com/users/iHateAnimeBro) is still stuck at December 2023, sort of like the project took a dump some time in 2024.

Thank you for checking! I really like the github-like heat map and I was curious to see mine.

**Comment by andersonkrs** [comment]
@Shark-93 I was moving some backups around and doing some maintance that's probably why you have seen some content missing text.

Can you confirm your profile is now updating correctly?

**Comment by Shark-93** [comment]
Yes, I confirm that. This issue though was opened in regards to an incorrectly coded hyperlink on every user's profile page, I am afraid it doesn't have to do with our profile data. Here, I will put a GIF of the problem reported by @cyber-sec0 so that there's no misunderstanding:
![the faq hyperlink has problem](https://github.com/andersonkrs/malheatmap/assets/25310397/0ba43de7-b21e-4449-8686-49155267cc04)

**Comment by andersonkrs** [comment]
@Shark-93 Appreciate the explanation!

The link has been fixed cc @cyber-sec0
